prep-javascript-conditionals - Heerak Moon
hmoon2/prep-0922-code-solutions pull request #14
Opened 2022-09-29 21:22 UTC by hmoon2

![prep-javascript-conditionals](https://user-images.githubusercontent.com/113075380/193144441-82cb9a56-4169-488e-8502-8a743c2624f8.JPG)

2022-09-29 22:36 UTC, thebearingedge requested changes

2022-09-29 22:36 UTC, thebearingedge commented on prep-javascript-conditionals/index.html
> +      console.log('Have a good weekend!');
To make this work we need a comparison expression on both sides of the `||` "or" operator

```js
if (dayOfTheWeek === 'Saturday' || dayOfTheWeek === 'Sunday') {
```

2022-09-29 23:46 UTC, hmoon2 commented on prep-javascript-conditionals/index.html
> +      console.log('Have a good weekend!');
![prep-javascript-conditionals-updated](https://user-images.githubusercontent.com/113075380/193161022-e09509d5-0175-485a-8ce7-236457254b16.JPG)

2022-09-30 00:32 UTC, thebearingedge approved these changes

2022-09-30 18:45 UTC, merged